name: Four PR Test Workflow

on:
  pull_request:
    branches:
      - main
      - master
      - stage

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test
